---
- name: SET var credential
  set_fact:
    var_credential:
      username: "nap@f5cloudbuilder.dev"
      password: "NGINXC0ntroller!"

- name: CREATE VMSS Extension
  delegate_to: localhost
  azure_rm_virtualmachinescalesetextension:
    resource_group: "rg-{{ extra_platform_name }}"
    vmss_name: "{{ extra_vmss_name }}"
    name: "extension-{{ extra_vmss_name }}"
    location: "{{ extra_location }}"
    publisher: 'Microsoft.Azure.Extensions'
    type: 'CustomScript'
    type_handler_version: 2.0
    protected_settings:
      commandToExecute: "{{ lookup('template', 'nginx_managed_by_controller_bootstrapping.jinja2') }}"
#    settings: '{"fileUris": [
#    "{{ extra_app_protect_repo }}/app-protect-20.zip",
#    "{{ extra_app_protect_repo }}/installAppProtect.sh",
#    ]}'
    auto_upgrade_minor_version: true

- name: List VM instances in Virtual Machine ScaleSet
  delegate_to: localhost
  azure_rm_virtualmachinescalesetinstance_info:
    resource_group: "rg-{{ extra_platform_name }}"
    vmss_name: "{{ extra_vmss_name }}"
  register: output_vmss_instances

- name: Upgrade VMSS instances with Extension
  delegate_to: localhost
  azure_rm_virtualmachinescalesetinstance:
    resource_group: "rg-{{ extra_platform_name }}"
    vmss_name: "{{ extra_vmss_name }}"
    instance_id: "{{ item.instance_id }}"
    latest_model: true
  loop: "{{ output_vmss_instances.instances }}"
  register: output_vmss_instances_extension

- name: CMP OUTPUT
  debug:
    msg: "
    key={{ item.item.name }} provisioning state;value={{ item.item.provisioning_state }};help=VM
    key={{ item.item.name }} power state;value={{ item.item.power_state }};help=VM
    "
  loop: "{{ output_vmss_instances_extension.results }}"
  loop_control:
    index_var: cur_index
...