---
# PREPARE multi-AS3 call - https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/miscellaneous.html#sending-multiple-declarations-in-a-single-request-big-iq
- name: INIT var_multi_as3
  set_fact:
    var_multi_as3: []

- name: SET var_multi_as3
  set_fact:
    var_multi_as3: "{{ var_multi_as3 }} + [{{ lookup('template', '{{ extra_as3_template }}') }}]"
  loop: "{{ stats_self_ips }}"
  when: item.protect_from_scale_in == "True"

- debug:
    var: var_multi_as3

- name: Get BIG-IQ Token
  uri:
    url: "https://{{ extra_bigiq_ip_mgt }}:{{ extra_bigiq_port_mgt }}/mgmt/shared/authn/login"
    method: POST
    headers:
      Content-Type: application/json
    body: "{{ lookup('template','bigiq_auth.jinja2') }}"
    body_format: json
    timeout: 60
    status_code: 200, 202
    validate_certs: false
  register: auth

# DEPLOY https://clouddocs.f5.com/products/big-iq/mgmt-api/v7.0.0/ApiReferences/bigiq_public_api_ref/r_as3_declare.html
- name: DEPLOY AS3
  uri:
    url: "https://{{ extra_bigiq_ip_mgt }}:{{ extra_bigiq_port_mgt }}/mgmt/shared/appsvcs/declare?async=true"
    method: POST
    headers:
        X-F5-Auth-Token: "{{auth.json.token.token}}"
    body: "{{ var_multi_as3 }}"
    body_format: json
    timeout: 60
    status_code: 200, 202
    validate_certs: false
  register: response_deploy_as3

- debug:
    var: response_deploy_as3.json

- name: WAIT for AS3 Deployment in progress
  uri:
    url: https://{{ extra_bigiq_ip_mgt }}:{{ extra_bigiq_port_mgt }}/mgmt/shared/appsvcs/task/{{response_deploy_as3.json.id}}
    method: GET
    headers:
      X-F5-Auth-Token: "{{auth.json.token.token}}"
    timeout: 60
    status_code: 200
    validate_certs: false
  until: "response_check_as3.json.results[0].code == 200"
  retries: 5
  delay: 15
  register: response_check_as3

- debug:
    var: response_check_as3







...