---
- name: SET var_failoverGroup_master_dataplane
  set_fact:
    var_failoverGroup_master_dataplane: "{{ stats_self_ips.0.dataplane }}"
  loop: "{{ stats_self_ips }}"
  when: item.protect_from_scale_in == "True"

- name: INIT var_failoverGroup_members
  set_fact:
    var_failoverGroup_members: []

- name: SET var_failoverGroup_members
  set_fact:
    var_failoverGroup_members: "{{ var_failoverGroup_members + [ item.dataplane ] }}"
  loop: "{{ stats_self_ips }}"

- name: var_failoverGroup_members
  debug:
    msg: "var_failoverGroup_members: {{ var_failoverGroup_members }}"

- name: do-vmss-master-2nic-awaf-BIGIQ.json
  debug:
    msg: "{{ lookup('template', 'do-vmss-master-2nic-awaf-BIGIQ.json') }}"
  loop: "{{ stats_self_ips }}"
  when: item.protect_from_scale_in == "True"

- name: Get BIG-IQ Token
  uri:
    url: "https://{{ extra_bigiq_ip_mgt }}:{{ extra_bigiq_port_mgt }}/mgmt/shared/authn/login"
    method: POST
    headers:
      Content-Type: application/json
    body: "{{ lookup('template','bigiq_auth.jinja2') }}"
    body_format: json
    timeout: 60
    status_code: 200, 202
    validate_certs: false
  register: auth

- name: onboarding Master only when slaves exists
  uri:
    url: https://{{ extra_bigiq_ip_mgt }}:{{ extra_bigiq_port_mgt }}/mgmt/shared/declarative-onboarding
    method: "POST"
    headers:
        X-F5-Auth-Token: "{{auth.json.token.token}}"
    validate_certs: no
    body: "{{ lookup('template', 'do-vmss-master-2nic-awaf-BIGIQ.json') }}"
    body_format: json
    timeout: 300
    status_code: 200, 202
  register: list_json_response
  loop: "{{ stats_self_ips }}"
  when:
    - item.protect_from_scale_in == "True"
    - ansible_loop.length > 1
  loop_control:
    extended: yes

- name: onboarding Master only when slaves absent
  uri:
    url: https://{{ extra_bigiq_ip_mgt }}:{{ extra_bigiq_port_mgt }}/mgmt/shared/declarative-onboarding
    method: "POST"
    headers:
        X-F5-Auth-Token: "{{auth.json.token.token}}"
    validate_certs: no
    body: "{{ lookup('template', 'do-vmss-master_alone-2nic-awaf-BIGIQ.json') }}"
    body_format: json
    timeout: 300
    status_code: 200, 202
  register: list_json_response
  loop: "{{ stats_self_ips }}"
  when:
    - item.protect_from_scale_in == "True"
    - ansible_loop.length == 1
  loop_control:
    extended: yes

- debug:
    var: list_json_response

- pause:
    minutes: 10

- name: Get BIG-IQ Token
  uri:
    url: "https://{{ extra_bigiq_ip_mgt }}:{{ extra_bigiq_port_mgt }}/mgmt/shared/authn/login"
    method: POST
    headers:
      Content-Type: application/json
    body: "{{ lookup('template','bigiq_auth.jinja2') }}"
    body_format: json
    timeout: 60
    status_code: 200, 202
    validate_certs: false
  register: auth

- name: onboarding Slave
  uri:
    url: https://{{ extra_bigiq_ip_mgt }}:{{ extra_bigiq_port_mgt }}/mgmt/shared/declarative-onboarding
    method: "POST"
    headers:
        X-F5-Auth-Token: "{{auth.json.token.token}}"
    validate_certs: no
    body: "{{ lookup('template', 'do-vmss-slave-2nic-awaf-BIGIQ.json') }}"
    body_format: json
    timeout: 300
    status_code: 200, 202
  loop: "{{ stats_self_ips }}"
  when: item.protect_from_scale_in != "True"

- name: CMP_OUTPUT
  debug:
    msg: "
    key=do_log_file;value=/var/log/restnoded/restnoded.log;help=restnoded failure log;
    "

- pause:
    prompt: "Please wait during BIG-IP load modules"
    minutes: 10

...
